development:
 adapter: postgresql
 database: blogapp_development
 pool: 5
 timeout: 5000

test:
 adapter: postgresql
 database: blogapp_test
 pool: 5
 timeout: 5000

production:
 adapter: postgresql
 database: blogapp_production
 pool: 5
 timeout: 5000